using System;
using System.Drawing;
using System.Linq;
using PowerLanguage.Function;

namespace PowerLanguage.Indicator
{
    public class __SherNing_TrendCatcher : IndicatorObject
    {
        //==========================================================================================
        // Name           : __SherNing_TrendCatcher
        // Description    : Trend Catcher Indicator
        // Version        : v1.0
        // Date Created   : 28 - Jul - 2020
        // Time Taken     : 
        // Remarks        :
        //==========================================================================================
        // Copyright      : 2020, Sher Ning Technologies           
        // License        :      
        //==========================================================================================

        /*  ----------------------------------- Version History -----------------------------------
         *  
         *  ----------------------------------- Version History -----------------------------------


         *  ------------------------------------ Project Notes ------------------------------------
         *  - 
         *  
         *  ------------------------------------ Project Notes ------------------------------------
         */
        public __SherNing_TrendCatcher(object _ctx) : base(_ctx) { }
        protected override void Create()
        {
        }
        protected override void StartCalc()
        {
        }
        protected override void CalcBar()
        {
        }
    }
}