using System;
using System.Drawing;
using System.Linq;
using PowerLanguage.Function;
using ATCenterProxy.interop;

namespace PowerLanguage.Strategy
{
    //==========================================================================================
    // Name           : Strategy to Broker
    // Description    : Understand what is under the hood
    // Version        : v.1.0
    // Date Created   : 24 - Jun - 2020
    // Time Taken     : 
    // Remarks        :
    //==========================================================================================
    // Copyright      : 2020, Sher Ning Technologies           
    // License        :      
    //==========================================================================================

    /*  ----------------------------------- Version History -----------------------------------
     *  v.1.0
     *  - Toolbar Support
     *  ----------------------------------- Version History -----------------------------------

     *  ---------------------------------------- Notes ----------------------------------------
     *   - Learning to manage real-time data.
     *  ---------------------------------------- Notes ----------------------------------------
     */
    public class __SherNing_StrategyToBroker : SignalObject
    {
        public __SherNing_StrategyToBroker(object _ctx) : base(_ctx) { }
        protected override void Create()
        {
        }
        protected override void StartCalc()
        {
        }
        protected override void CalcBar()
        {
        }
    }
}